### ISSUE TITLE
검색 select태그 & 작성자 표시, 검색

### ISSUE THREAD

**Issue by hyeokjulee** [BeomSeokYu/Save-The-Web#22]
1. 각 게시판 검색 select태그의 option들 통일 필요
2. 작성자 이름으로 표시할지 이메일로 표시할지에 따라 작성자 검색 어떻게 해야할지 달라지므로 고민 필요

**Comment by dawnpoems** [comment]
이메일 제외하고 제목/내용 혹은 제목/내용/설교자로만 검색 가능하게 하겠음
진행중

**Comment by dawnpoems** [comment]
해결!
